AppBundle\Entity\Category:
    type:  entity
    table: categories
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
    oneToMany:
        products:
            targetEntity: Product
            mappedBy: category