AppBundle\Entity\Tag:
    type:  entity
    table: tags
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
    manyToMany:
        products:
            targetEntity: Product
            inversedBy: tags